'use client';
import { useState } from 'react';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import Photo from '@/components/photo';
import CameraScrollIntro from '@/components/camera-scroll-intro';
import { ArrowDown, ArrowUpRight, Play } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
const films = [
{ id:'-T_E8705WKM',title:'SHABBAT SESH',subtitle:'A skate video by Arthur Khitrik',category:'Skate film'},
{ id:'a_6WP38cPLs',title:'H-TOWN ADVENTURES',subtitle:'RVCA Israel',category:'On the road'},
{ id:'J6dvfCfBzL4',title:'EVYATAR TAHAR',subtitle:'Welcome to Spicy Grips',category:'Welcome part'},
{ id:'3P2LnFrUu0U',title:'N9 IN PARIS',subtitle:'N9 trip to Paris, 2025',category:'On the road'},
{ id:'RMm_e1s54A8',title:'GO SKATE DAY',subtitle:"Tel Aviv, 2026 · Gili's Skate Shop",category:'Skate film'},
{ id:'_tyHrUSh6GI',title:'JIN-G DROPS',subtitle:'Ramat Hachayal Skatepark',category:'Skate film'}];
export default function Home(){
const [active,setActive]=useState<number|null>(null); const film=active===null?null:films[active];
return <><a className="skip-link" href="#work">Skip to films</a>
<CameraScrollIntro/>
<div id="site-start" tabIndex={-1}><SiteHeader/></div>
<main id="top"><section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="record-dot"/> BEHIND THE LENS. IN THE EDIT.</p><h1 id="hero-title">ARTHUR<br/><span>KHITRIK.</span></h1><p className="hero-description">Skateboarding. People. Places.<br/>Films from the streets, made to be felt.</p><a className="work-link" href="#work">TAKE A LOOK <ArrowDown size={18}/></a></div>
<div className="hero-art"><div className="paper-back" aria-hidden="true"><span>FIELD NOTES / 001</span><span>KEEP ROLLING.</span></div><button className="hero-cover" onClick={()=>setActive(0)} aria-label="Play SHABBAT SESH"><span className="tape" aria-hidden="true"/><span className="cover-top"><span>AN ARTHUR KHITRIK FILM</span><span>▶ REC</span></span><span className="hero-image"><img src="https://i.ytimg.com/vi/-T_E8705WKM/hqdefault.jpg" alt="SHABBAT SESH skate film cover" fetchPriority="high"/><span className="cover-play"><Play fill="currentColor" size={24}/></span></span><span className="cover-title">SHABBAT<br/>SESH<span>↗</span></span><span className="cover-bottom"><span>SKATEBOARDING / FILM / FRIENDS</span><span>01</span></span></button><span className="handwritten" aria-hidden="true">press play ↗</span><div className="film-sticker" aria-hidden="true">FILM IT.<span>AK © 2026</span></div></div>
<a className="feature-story-link" href="/shabbat-sesh">THE SHABBAT SESH STORY ↗</a><div className="hero-footer"><span>INDEPENDENT FILMMAKING</span><span>SCROLL FOR THE GOOD STUFF <ArrowDown size={14}/></span></div></section>
<section id="work" className="work-section" aria-labelledby="work-title"><div className="section-heading"><div><p className="eyebrow">ARCHIVE</p><h2 id="work-title">SELECTED WORKS</h2></div><p>Out in the streets.<br/>Back in the timeline.</p></div><div className="film-grid">{films.map((item,index)=><article className="film" key={item.id}><button className="film-preview" onClick={()=>setActive(index)} aria-label={`Play ${item.title}`}><img src={index===1 ? "/photos/06-1600.webp" : `https://i.ytimg.com/vi/${item.id}/hqdefault.jpg`} alt={item.subtitle} loading="lazy"/><span className="film-number">{String(index+1).padStart(2,'0')} / 06</span><span className="play-circle"><Play size={20} fill="currentColor"/></span><span className="preview-label">WATCH FILM <ArrowUpRight size={15}/></span></button><div className="film-info"><div><h3><button onClick={()=>setActive(index)}>{item.title}</button></h3><p>{item.subtitle}</p></div><span className="category">{item.category}</span></div></article>)}</div></section>
<section id="about" className="about-section" aria-labelledby="about-title"><div className="about-heading"><p className="eyebrow">ON EITHER SIDE OF THE CUT</p><h2 id="about-title">ALWAYS<br/>ROLLING<span>.</span></h2><span className="handwritten about-script">Arthur Khitrik</span><a className="about-page-link" href="/about">MORE ABOUT ME ↗</a><Photo id={1} alt="Arthur holding his camera at the skatepark" className="about-portrait"/></div><div className="about-note"><span className="tape" aria-hidden="true"/><p className="note-label">A NOTE FROM ARTHUR</p><p>I'm a videographer and editor.<br/>You'll usually find me following a session, chasing a shot, or piecing it all together in the edit.</p><p>This is a selection of films I've worked on. Hit play and stay for a while.</p><a href="https://www.youtube.com/@arthurkhitrik2360" target="_blank" rel="noreferrer">MORE ON YOUTUBE <ArrowUpRight size={18}/></a></div></section></main>
<SiteFooter/>
<Dialog open={active!==null} onOpenChange={open=>{if(!open)setActive(null)}}><DialogContent className="w-[calc(100%-2rem)] sm:max-w-5xl p-5"><DialogTitle>{film?.title??'Watch film'}</DialogTitle><DialogDescription>{film?.subtitle}</DialogDescription>{film&&<><iframe className="youtube-player" key={film.id} src={`https://www.youtube-nocookie.com/embed/${film.id}?autoplay=1&playsinline=1&rel=0`} title={film.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/><a className="youtube-fallback" href={`https://www.youtube.com/watch?v=${film.id}`} target="_blank" rel="noreferrer">Watch on YouTube <ArrowUpRight size={16}/></a></>}</DialogContent></Dialog></>;
}
