'use client';
import {useState} from 'react';
import {Mail, ArrowUpRight} from 'lucide-react';
import {Field,FieldGroup,FieldLabel,FieldDescription} from '@/components/ui/field';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Button} from '@/components/ui/button';
export default function Contact({email}:{email:string}){
const [draftOpened,setDraftOpened]=useState(false);
function compose(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!email)return;const data=new FormData(event.currentTarget);const name=String(data.get('name')||'').trim();const message=String(data.get('message')||'').trim();if(!message)return;const subject=`Website enquiry${name?' from '+name:''}`;const body=`Hi Arthur,\n\n${message}${name?'\n\n'+name:''}`;window.location.href=`mailto:${email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;setDraftOpened(true)}
return <section id="contact" className="contact-section" aria-labelledby="contact-title"><div className="contact-heading"><p className="eyebrow">GOT SOMETHING IN MIND?</p><h2 id="contact-title">LEAVE A<br/>MESSAGE.</h2><p>A film, an edit, a session.<br/>Tell me what you're thinking.</p>{email&&<a className="contact-email" href={`mailto:${email}`}><Mail size={18}/>{email}</a>}</div><form onSubmit={compose} className="contact-form"><FieldGroup><Field><FieldLabel htmlFor="contact-name">Your name</FieldLabel><Input id="contact-name" name="name" autoComplete="name" maxLength={100} placeholder="Name"/></Field><Field><FieldLabel htmlFor="contact-message">Your message</FieldLabel><Textarea id="contact-message" name="message" required maxLength={3000} rows={5} placeholder="Tell me about your project..." aria-describedby="contact-help"/><FieldDescription id="contact-help">To: {email}. Opens your email app with this message. You must press Send there; this website does not send emails.</FieldDescription></Field><Button type="submit" size="lg" className="h-12 w-fit px-6" disabled={!email}>Open email draft <ArrowUpRight data-icon="inline-end"/></Button></FieldGroup>{draftOpened&&<p className="contact-status" role="status">Your draft is ready to open in your email app. If it didn't open, copy your message and email <a href={`mailto:${email}`}>{email}</a>.</p>}</form></section>}
