import type {Metadata} from 'next';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import Photo from '@/components/photo';
import FeatureFilm from '@/components/feature-film';
import styles from './title.module.css';
export const metadata:Metadata={title:'SHABBAT SESH | Arthur Khitrik',description:'Watch SHABBAT SESH, meet the crew and revisit the September 2025 premiere at Gilis Skateshop in Tel Aviv.'};
const premiere=[{id:14,alt:'The crowd gathered for the premiere at Gilis'},{id:9,alt:'A black and white photograph of the premiere audience'},{id:21,alt:'The crew holding a skate photograph at the premiere'},{id:22,alt:'Sharing a printed skate photograph after the screening'},{id:23,alt:'A skater receiving his SHABBAT SESH print'},{id:24,alt:'Celebrating with a printed photograph at Gilis'}];
export default function ShabaSesh(){return <><SiteHeader/><main id="top" className="sesh-page"><section className="sesh-hero"><div><p className="eyebrow">A FILM BY ARTHUR KHITRIK / 2025</p><h1 className={styles.title}><img src="/shabbat-sesh-title.jpg" alt="SHABBAT SESH" width={1024} height={1024} fetchPriority="high" /></h1><p className="sesh-intro">The sessions.<br/>The people.<br/>The night we put it on screen.</p><a className="work-link" href="#film">WATCH SHABBAT SESH ↓</a></div><figure className="sesh-poster"><Photo id={5} alt="Original SHABBAT SESH premiere poster, 18 September 2025" priority/><figcaption>THE ORIGINAL PREMIERE POSTER / 18.09.2025</figcaption></figure></section><FeatureFilm/>
<section className="story-section"><div><p className="eyebrow">18 SEPTEMBER 2025 / TEL AVIV</p><h2>FROM GOLDA<br/>TO GILIS.</h2></div><div className="story-copy"><p>The day started at Golda Spot with a pre-premiere session and an under-18 best trick contest, supported by Vans and Monster Energy.</p><p>Then we headed to Gilis Skateshop. Hiffi's “HABITA” and Eden Gil's new part for Mudcan opened the screening before SHABBAT SESH took over the screen.</p><p>Thank you to Gilis for hosting and Herzl Beer for the drinks.</p><a className="text-link" href="https://truesk8boardmag.com/shabbatsesh/" target="_blank" rel="noreferrer">Also featured in True Sk8board Mag ↗</a></div></section>

<section className="credits-section"><div><p className="eyebrow">ON THE BOARDS</p><p>Yovel Hamami · Evyatar Tahar · Salamon Tadasa · Omri Edri · Arthur Khitrik · Daniel Nekhamkin · Ben Levy · Gil Kressel · Tim Krestol</p></div><div><p className="eyebrow">FILMING & EDITING CREDITS</p><p>Arthur Khitrik · Noam Maimon · Ben Levy · Gil Kressel · David Doh Doh Rosen</p><p className="photo-credit">Event photography: Noam Maimon</p></div></section>
<section className="premiere-section"><div className="section-heading"><div><p className="eyebrow">GILIS SKATESHOP</p><h2>PREMIERE NIGHT.</h2></div><span className="eyebrow">18.09.2025</span></div><div className="premiere-gallery">{premiere.map(p=><figure key={p.id}><Photo {...p}/></figure>)}</div></section><a className="next-story" href="/blog/behind-the-camera"><span className="eyebrow">MORE FROM THE ARCHIVE</span><h2>BEHIND THE CAMERA ↗</h2></a></main><SiteFooter/></>}
